[package]
edition = "2018"
name = "a2020"
version = "0.1.0"
authors = ["Juergen Stuber <juergen@jstuber.net>"]

[dependencies]
ena = "0.5.0"
nom = "4.1.1"
num = "0.2.0"
num-integer = "0.1.41"
rand = "0.6.0"
twodim = { path = "../../twodim", version = "0.1.0" }
gamedim = { path = "../../gamedim", version = "0.1.0" }
