[package]
edition = "2021"
name = "a2017"
version = "0.1.0"
authors = ["Juergen Stuber <juergen@jstuber.net>"]

[dependencies]
num = "0.4.0"
num-integer = "0.1.44"
rand = "0.8.4"
lowdim = "0.3.1"
nom = "7.0.0"
util = { path = "../util" }
primal = "0.3.0"
