[package]
edition = "2021"
name = "a2023"
version = "0.1.0"
authors = ["Juergen Stuber <juergen@jstuber.net>"]
license = "MIT OR Apache-2.0"

[dependencies]
nom = "7.0.0"
num = "0.4.0"
lowdim = "0.6.0"
util = { path = "../util" }
pathfinding = "2.2.2"
