[package]
edition = "2021"
name = "a2021"
version = "0.1.0"
authors = ["Juergen Stuber <juergen@jstuber.net>"]

[dependencies]
nom = "7.0.0"
lowdim = "0.5.2"
util = { path = "../util" }
pathfinding = "2.2.2"
