[package]
edition = "2018"
name = "a2018"
version = "0.1.0"
authors = ["Juergen Stuber <juergen@jstuber.net>"]

[dependencies]
nom = "6.2.1"
num = "0.2.0"
num-integer = "0.1.41"
rand = "0.8.1"
pathfinding = "2.1.6"
gamedim = { path = "../../gamedim", version = "0.2.0" }
