[package]
edition = "2021"
name = "a2018"
version = "0.1.0"
authors = ["Juergen Stuber <juergen@jstuber.net>"]

[dependencies]
nom = "7.0.0"
num = "0.4.0"
num-integer = "0.1.44"
rand = "0.8.4"
pathfinding = "2.2.2"
lowdim = "0.5.4"
util = { path = "../util" }
